# Generated by Django 4.2 on 2024-11-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('deleted_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted time')),
                ('deleted', models.BooleanField(default=False, editable=False, verbose_name='deleted')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit Addition'), ('charge', 'Recharge Sale')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('INQUIRY_PENDING', 'INQUIRY_PENDING'), ('DONE', 'DONE'), ('CANCEL', 'CANCEL'), ('TRANSACTION_FAILED', 'TRANSACTION_FAILED'), ('ORDER_FAILED', 'ORDER_FAILED')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
